apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - backend
  - frontend

namespace: study-app
namePrefix: prod-

images:
  - name: backend
    newTag: backend-v0.2.0
  - name: frontend
    newTag: frontend-v0.1.0
